"""create members table

Revision ID: 4198b94a468b
Revises: d36aec4282fc
Create Date: 2026-05-29 21:48:55.657336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4198b94a468b'
down_revision: Union[str, Sequence[str], None] = 'd36aec4282fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('profile_image_url', sa.String(length=2048), nullable=True),
    sa.Column('collaborating_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['tax_code'], ['people.tax_code'], name=op.f('fk_members_tax_code_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
