"""implement constraints

Revision ID: 5653d8989dad
Revises: 722d7f548178
Create Date: 2026-06-02 23:32:25.909811

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5653d8989dad"
down_revision: str | Sequence[str] | None = "722d7f548178"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_participants",
        sa.Column("tax_code", sa.String(length=16), nullable=False),
        sa.Column("medical_certificate_expiration", sa.Date(), nullable=False),
        sa.Column("course_type", sa.String(length=100), nullable=False),
        sa.CheckConstraint(
            "medical_certificate_expiration > DATE '1900-01-01'",
            name=op.f("ck_course_participants_medical_certificate_expiration_min"),
        ),
        sa.CheckConstraint(
            "course_type IS NULL OR course_type = btrim(course_type)",
            name=op.f("ck_course_participants_course_type_no_surrounding_whitespace"),
        ),
        sa.CheckConstraint(
            "length(trim(course_type)) > 0",
            name=op.f("ck_course_participants_course_type_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["tax_code"],
            ["members.tax_code"],
            name=op.f("fk_course_participants_tax_code_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tax_code", name=op.f("pk_course_participants")),
    )
    op.drop_table("trainees")
    op.create_index(
        "uq_administrator_president",
        "administrators",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'PRESIDENT'"),
    )
    op.create_index(
        "uq_administrator_treasurer",
        "administrators",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'TREASURER'"),
    )
    op.create_index(
        "uq_administrator_vice_president",
        "administrators",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'VICE_PRESIDENT'"),
    )
    op.drop_constraint(
        op.f("uq_memberships_member_tax_code"), "memberships", type_="unique"
    )
    op.create_unique_constraint(
        "uq_membership_member_year", "memberships", ["member_tax_code", "year"]
    )
    op.add_column(
        "school_enrollments",
        sa.Column("teaching_offering_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        op.f("uq_school_enrollments_student_tax_code"),
        "school_enrollments",
        type_="unique",
    )
    op.create_index(
        op.f("ix_school_enrollments_teaching_offering_id"),
        "school_enrollments",
        ["teaching_offering_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_student_school_year",
        "school_enrollments",
        ["student_tax_code", "start_year"],
    )
    op.create_foreign_key(
        op.f("fk_school_enrollments_teaching_offering_id_teaching_offerings"),
        "school_enrollments",
        "teaching_offerings",
        ["teaching_offering_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "schools",
        "mechanographic_code",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.create_unique_constraint("uq_study_program_name", "study_programs", ["name"])
    op.add_column(
        "subjects", sa.Column("specialization", sa.String(length=100), nullable=True)
    )
    op.drop_constraint(op.f("uq_subjects_discipline"), "subjects", type_="unique")
    op.create_index(
        "uq_subject_discipline_specialization",
        "subjects",
        [
            sa.literal_column("discipline"),
            sa.literal_column("COALESCE(specialization, '')"),
        ],
        unique=True,
    )
    op.drop_column("subjects", "area")
    op.alter_column(
        "teaching_offerings",
        "school_mechanographic_code",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_teaching_offering",
        "teaching_offerings",
        ["school_mechanographic_code", "study_program_id", "level"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_teaching_offering", "teaching_offerings", type_="unique")
    op.alter_column(
        "teaching_offerings",
        "school_mechanographic_code",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.add_column(
        "subjects",
        sa.Column("area", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.drop_index("uq_subject_discipline_specialization", table_name="subjects")
    op.create_unique_constraint(
        op.f("uq_subjects_discipline"),
        "subjects",
        ["discipline", "area"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("subjects", "specialization")
    op.drop_constraint("uq_study_program_name", "study_programs", type_="unique")
    op.alter_column(
        "schools",
        "mechanographic_code",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_school_enrollments_teaching_offering_id_teaching_offerings"),
        "school_enrollments",
        type_="foreignkey",
    )
    op.drop_constraint("uq_student_school_year", "school_enrollments", type_="unique")
    op.drop_index(
        op.f("ix_school_enrollments_teaching_offering_id"),
        table_name="school_enrollments",
    )
    op.create_unique_constraint(
        op.f("uq_school_enrollments_student_tax_code"),
        "school_enrollments",
        ["student_tax_code", "start_year"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("school_enrollments", "teaching_offering_id")
    op.drop_constraint("uq_membership_member_year", "memberships", type_="unique")
    op.create_unique_constraint(
        op.f("uq_memberships_member_tax_code"),
        "memberships",
        ["member_tax_code", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        "uq_administrator_vice_president",
        table_name="administrators",
        postgresql_where=sa.text("role = 'VICE_PRESIDENT'"),
    )
    op.drop_index(
        "uq_administrator_treasurer",
        table_name="administrators",
        postgresql_where=sa.text("role = 'TREASURER'"),
    )
    op.drop_index(
        "uq_administrator_president",
        table_name="administrators",
        postgresql_where=sa.text("role = 'PRESIDENT'"),
    )
    op.create_table(
        "trainees",
        sa.Column(
            "tax_code", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
        sa.Column(
            "medical_certificate_expiration",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "course_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "medical_certificate_expiration > '1900-01-01'::date",
            name=op.f("ck_trainees_medical_certificate_expiration_min"),
        ),
        sa.ForeignKeyConstraint(
            ["tax_code"],
            ["members.tax_code"],
            name=op.f("fk_trainees_tax_code_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tax_code", name=op.f("pk_trainees")),
    )
    op.drop_table("course_participants")
    # ### end Alembic commands ###
