"""create memberships table

Revision ID: 5884ba8fe816
Revises: 4198b94a468b
Create Date: 2026-05-29 21:59:48.706260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5884ba8fe816'
down_revision: Union[str, Sequence[str], None] = '4198b94a468b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tax_code', sa.String(length=16), nullable=False),
    sa.Column('revocation', sa.Enum('NO', 'EXPULSION', 'RESIGNATION', name='membership_revocation_enum'), server_default='NO', nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('renewal_period_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                revocation = 'NO'\n                AND renewal_period_days > 0\n            )\n            OR\n            (\n                revocation IN ('EXPULSION', 'RESIGNATION')\n                AND renewal_period_days = 0\n            )\n            ", name=op.f('ck_memberships_membership_renewal_period_consistency')),
    sa.CheckConstraint("start_date > DATE '1900-01-01'", name=op.f('ck_memberships_membership_start_date_min')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_memberships_membership_end_after_start')),
    sa.CheckConstraint('id > 0', name=op.f('ck_memberships_positive_id')),
    sa.CheckConstraint('year >= 1900', name=op.f('ck_memberships_membership_year_min')),
    sa.ForeignKeyConstraint(['member_tax_code'], ['members.tax_code'], name=op.f('fk_memberships_member_tax_code_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('member_tax_code', 'year', name=op.f('uq_memberships_member_tax_code'))
    )
    op.create_index(op.f('ix_memberships_member_tax_code'), 'memberships', ['member_tax_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_member_tax_code'), table_name='memberships')
    op.drop_table('memberships')
    # ### end Alembic commands ###
