"""replace teacher offering with teaching competence

Revision ID: 5abee1e46f43
Revises: 8fc0e845e1ab
Create Date: 2026-06-14 22:50:31.961013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abee1e46f43'
down_revision: Union[str, Sequence[str], None] = '8fc0e845e1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_competences',
    sa.Column('teacher_tax_code', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teaching_offering_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teaching_competences_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_tax_code'], ['teachers.tax_code'], name=op.f('fk_teaching_competences_teacher_tax_code_teachers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_offering_id'], ['teaching_offerings.id'], name=op.f('fk_teaching_competences_teaching_offering_id_teaching_offerings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_tax_code', 'subject_id', 'teaching_offering_id', name=op.f('pk_teaching_competences'))
    )
    op.drop_table('teacher_offerings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_offerings',
    sa.Column('teacher_tax_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('teaching_offering_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_tax_code'], ['teachers.tax_code'], name=op.f('fk_teacher_offerings_teacher_tax_code_teachers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_offering_id'], ['teaching_offerings.id'], name=op.f('fk_teacher_offerings_teaching_offering_id_teaching_offerings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_tax_code', 'teaching_offering_id', name=op.f('pk_teacher_offerings'))
    )
    op.drop_table('teaching_competences')
    # ### end Alembic commands ###
