"""initial schema

Revision ID: 722d7f548178
Revises: 
Create Date: 2026-06-01 23:38:03.795486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722d7f548178'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_city', sa.String(length=100), nullable=False),
    sa.Column('birth_province', sa.String(length=2), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('residence_type', sa.String(length=100), nullable=False),
    sa.Column('residence_address', sa.String(length=255), nullable=False),
    sa.Column('residence_street_number', sa.String(length=20), nullable=False),
    sa.Column('residence_city', sa.String(length=100), nullable=False),
    sa.Column('residence_province', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("birth_date >= DATE '1900-01-01'", name=op.f('ck_people_birth_date_min')),
    sa.CheckConstraint("birth_province ~ '^[A-Za-z]{2}$'", name=op.f('ck_people_birth_province_format')),
    sa.CheckConstraint("phone ~ '^\\+?[0-9]+$'", name=op.f('ck_people_phone_format')),
    sa.CheckConstraint("postal_code ~ '^[0-9]{5}$'", name=op.f('ck_people_postal_code_format')),
    sa.CheckConstraint("residence_province ~ '^[A-Za-z]{2}$'", name=op.f('ck_people_residence_province_format')),
    sa.CheckConstraint('birth_date <= CURRENT_DATE', name=op.f('ck_people_birth_date_max')),
    sa.CheckConstraint('length(tax_code) = 16', name=op.f('ck_people_tax_code_length')),
    sa.CheckConstraint('tax_code = upper(tax_code)', name=op.f('ck_people_tax_code_uppercase')),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_people'))
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    op.create_table('schools',
    sa.Column('mechanographic_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=False),
    sa.CheckConstraint("province ~ '^[A-Za-z]{2}$'", name=op.f('ck_schools_school_province_format')),
    sa.PrimaryKeyConstraint('mechanographic_code', name=op.f('pk_schools'))
    )
    op.create_table('study_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.CheckConstraint('id > 0', name=op.f('ck_study_programs_positive_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_programs'))
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.CheckConstraint('id > 0', name=op.f('ck_subjects_positive_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('discipline', 'area', name=op.f('uq_subjects_discipline'))
    )
    op.create_table('accounts',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='account_status_enum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_failed_login_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            locked_until IS NULL\n            OR last_failed_login_attempt IS NULL\n            OR locked_until >= last_failed_login_attempt\n            ', name=op.f('ck_accounts_locked_until_after_failed_attempt')),
    sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_accounts_failed_login_attempts_non_negative')),
    sa.ForeignKeyConstraint(['tax_code'], ['people.tax_code'], name=op.f('fk_accounts_tax_code_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('members',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('profile_image_url', sa.String(length=2048), nullable=True),
    sa.Column('collaborating_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['tax_code'], ['people.tax_code'], name=op.f('fk_members_tax_code_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_members'))
    )
    op.create_table('parents',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tax_code'], ['people.tax_code'], name=op.f('fk_parents_tax_code_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_parents'))
    )
    op.create_table('teaching_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('PRIMARY_SCHOOL', 'MIDDLE_SCHOOL', 'HIGH_SCHOOL', name='education_level_enum'), nullable=False),
    sa.Column('school_mechanographic_code', sa.String(length=20), nullable=False),
    sa.Column('study_program_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('id > 0', name=op.f('ck_teaching_offerings_positive_id')),
    sa.ForeignKeyConstraint(['school_mechanographic_code'], ['schools.mechanographic_code'], name=op.f('fk_teaching_offerings_school_mechanographic_code_schools'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], name=op.f('fk_teaching_offerings_study_program_id_study_programs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_offerings'))
    )
    op.create_index(op.f('ix_teaching_offerings_school_mechanographic_code'), 'teaching_offerings', ['school_mechanographic_code'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tax_code', sa.String(length=16), nullable=False),
    sa.Column('revocation', sa.Enum('NO', 'EXPULSION', 'RESIGNATION', name='membership_revocation_enum'), server_default='NO', nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('renewal_period_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                revocation = 'NO'\n                AND renewal_period_days > 0\n            )\n            OR\n            (\n                revocation IN ('EXPULSION', 'RESIGNATION')\n                AND renewal_period_days = 0\n            )\n            ", name=op.f('ck_memberships_membership_renewal_period_consistency')),
    sa.CheckConstraint("start_date > DATE '1900-01-01'", name=op.f('ck_memberships_membership_start_date_min')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_memberships_membership_end_after_start')),
    sa.CheckConstraint('id > 0', name=op.f('ck_memberships_positive_id')),
    sa.CheckConstraint('year >= 1900', name=op.f('ck_memberships_membership_year_min')),
    sa.ForeignKeyConstraint(['member_tax_code'], ['members.tax_code'], name=op.f('fk_memberships_member_tax_code_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('member_tax_code', 'year', name=op.f('uq_memberships_member_tax_code'))
    )
    op.create_index(op.f('ix_memberships_member_tax_code'), 'memberships', ['member_tax_code'], unique=False)
    op.create_table('parental_responsibilities',
    sa.Column('parent_tax_code', sa.String(length=16), nullable=False),
    sa.Column('child_tax_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['child_tax_code'], ['people.tax_code'], name=op.f('fk_parental_responsibilities_child_tax_code_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_tax_code'], ['parents.tax_code'], name=op.f('fk_parental_responsibilities_parent_tax_code_parents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_tax_code', 'child_tax_code', name=op.f('pk_parental_responsibilities'))
    )
    op.create_table('staff',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('collaboration_type', sa.Enum('VOLUNTEER', 'PAID', 'PCTO', name='collaboration_type_enum'), nullable=False),
    sa.Column('iban', sa.String(length=27), nullable=True),
    sa.CheckConstraint("\n            iban IS NULL\n            OR iban ~ '^IT[0-9]{2}[A-Z][0-9]{10}[A-Z0-9]{12}$'\n            ", name=op.f('ck_staff_iban_format')),
    sa.CheckConstraint('\n            iban IS NULL\n            OR iban = upper(iban)\n            ', name=op.f('ck_staff_iban_uppercase')),
    sa.CheckConstraint('\n            iban IS NULL\n            OR length(iban) = 27\n            ', name=op.f('ck_staff_iban_length')),
    sa.ForeignKeyConstraint(['tax_code'], ['members.tax_code'], name=op.f('fk_staff_tax_code_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_staff'))
    )
    op.create_table('students',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('authorized_early_exit', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['tax_code'], ['members.tax_code'], name=op.f('fk_students_tax_code_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_students'))
    )
    op.create_table('teaching_offering_subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teaching_offering_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teaching_offering_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_offering_id'], ['teaching_offerings.id'], name=op.f('fk_teaching_offering_subjects_teaching_offering_id_teaching_offerings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'teaching_offering_id', name=op.f('pk_teaching_offering_subjects'))
    )
    op.create_table('teaching_offering_years',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.CheckConstraint('year > 0', name=op.f('ck_teaching_offering_years_positive_year')),
    sa.CheckConstraint('year BETWEEN 1 AND 5', name=op.f('ck_teaching_offering_years_valid_school_year')),
    sa.ForeignKeyConstraint(['offering_id'], ['teaching_offerings.id'], name=op.f('fk_teaching_offering_years_offering_id_teaching_offerings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offering_id', 'year', name=op.f('pk_teaching_offering_years'))
    )
    op.create_table('trainees',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('medical_certificate_expiration', sa.Date(), nullable=False),
    sa.Column('course_type', sa.String(length=100), nullable=False),
    sa.CheckConstraint("medical_certificate_expiration > DATE '1900-01-01'", name=op.f('ck_trainees_medical_certificate_expiration_min')),
    sa.ForeignKeyConstraint(['tax_code'], ['members.tax_code'], name=op.f('fk_trainees_tax_code_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_trainees'))
    )
    op.create_table('administrators',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('PRESIDENT', 'VICE_PRESIDENT', 'TREASURER', 'OTHER', name='administrator_role_enum'), nullable=False),
    sa.Column('other_role', sa.String(length=100), nullable=True),
    sa.CheckConstraint("\n            (\n                role = 'OTHER'\n                AND other_role IS NOT NULL\n            )\n            OR\n            (\n                role <> 'OTHER'\n                AND other_role IS NULL\n            )\n            ", name=op.f('ck_administrators_other_role_consistency')),
    sa.ForeignKeyConstraint(['tax_code'], ['staff.tax_code'], name=op.f('fk_administrators_tax_code_staff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_administrators'))
    )
    op.create_table('psychologists',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tax_code'], ['staff.tax_code'], name=op.f('fk_psychologists_tax_code_staff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_psychologists'))
    )
    op.create_table('school_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('student_tax_code', sa.String(length=16), nullable=False),
    sa.CheckConstraint('id > 0', name=op.f('ck_school_enrollments_positive_id')),
    sa.CheckConstraint('start_year >= 1900', name=op.f('ck_school_enrollments_school_enrollment_start_year_min')),
    sa.ForeignKeyConstraint(['student_tax_code'], ['students.tax_code'], name=op.f('fk_school_enrollments_student_tax_code_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_enrollments')),
    sa.UniqueConstraint('student_tax_code', 'start_year', name=op.f('uq_school_enrollments_student_tax_code'))
    )
    op.create_index(op.f('ix_school_enrollments_student_tax_code'), 'school_enrollments', ['student_tax_code'], unique=False)
    op.create_table('teachers',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('school_education', sa.String(length=500), nullable=True),
    sa.Column('university_education', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tax_code'], ['staff.tax_code'], name=op.f('fk_teachers_tax_code_staff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_teachers'))
    )
    op.create_table('teacher_offerings',
    sa.Column('teacher_tax_code', sa.String(length=16), nullable=False),
    sa.Column('teaching_offering_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_tax_code'], ['teachers.tax_code'], name=op.f('fk_teacher_offerings_teacher_tax_code_teachers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_offering_id'], ['teaching_offerings.id'], name=op.f('fk_teacher_offerings_teaching_offering_id_teaching_offerings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_tax_code', 'teaching_offering_id', name=op.f('pk_teacher_offerings'))
    )
    op.create_table('teacher_subjects',
    sa.Column('teacher_tax_code', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_tax_code'], ['teachers.tax_code'], name=op.f('fk_teacher_subjects_teacher_tax_code_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_tax_code', 'subject_id', name=op.f('pk_teacher_subjects'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_subjects')
    op.drop_table('teacher_offerings')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_school_enrollments_student_tax_code'), table_name='school_enrollments')
    op.drop_table('school_enrollments')
    op.drop_table('psychologists')
    op.drop_table('administrators')
    op.drop_table('trainees')
    op.drop_table('teaching_offering_years')
    op.drop_table('teaching_offering_subjects')
    op.drop_table('students')
    op.drop_table('staff')
    op.drop_table('parental_responsibilities')
    op.drop_index(op.f('ix_memberships_member_tax_code'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_teaching_offerings_school_mechanographic_code'), table_name='teaching_offerings')
    op.drop_table('teaching_offerings')
    op.drop_table('parents')
    op.drop_table('members')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('subjects')
    op.drop_table('study_programs')
    op.drop_table('schools')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
