"""move profile image to accounts

Revision ID: 8fc0e845e1ab
Revises: 0d6c30e7fe00
Create Date: 2026-06-09 00:26:31.317858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc0e845e1ab'
down_revision: Union[str, Sequence[str], None] = '0d6c30e7fe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
