"""create parental responsibilities

Revision ID: 944c46894ef6
Revises: 97fcd934049e
Create Date: 2026-05-29 17:33:03.360694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944c46894ef6'
down_revision: Union[str, Sequence[str], None] = '97fcd934049e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tax_code'], ['people.tax_code'], name=op.f('fk_parents_tax_code_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_parents'))
    )
    op.create_table('parental_responsibilities',
    sa.Column('parent_tax_code', sa.String(length=16), nullable=False),
    sa.Column('child_tax_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['child_tax_code'], ['people.tax_code'], name=op.f('fk_parental_responsibilities_child_tax_code_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_tax_code'], ['parents.tax_code'], name=op.f('fk_parental_responsibilities_parent_tax_code_parents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_tax_code', 'child_tax_code', name=op.f('pk_parental_responsibilities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parental_responsibilities')
    op.drop_table('parents')
    # ### end Alembic commands ###
