"""create accounts table

Revision ID: 97fcd934049e
Revises: c4b8f5d8350b
Create Date: 2026-05-29 17:22:27.137007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fcd934049e'
down_revision: Union[str, Sequence[str], None] = 'c4b8f5d8350b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='account_status_enum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_failed_login_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            locked_until IS NULL\n            OR last_failed_login_attempt IS NULL\n            OR locked_until >= last_failed_login_attempt\n            ', name=op.f('ck_accounts_locked_until_after_failed_attempt')),
    sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_accounts_failed_login_attempts_non_negative')),
    sa.ForeignKeyConstraint(['tax_code'], ['people.tax_code'], name=op.f('fk_accounts_tax_code_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
