"""create people table

Revision ID: c4b8f5d8350b
Revises: 
Create Date: 2026-05-29 17:02:40.142130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b8f5d8350b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('tax_code', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_city', sa.String(length=100), nullable=False),
    sa.Column('birth_province', sa.String(length=2), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('parental_responsibility', sa.Enum('DEPENDENT', 'INDEPENDENT', name='parental_responsibility_enum'), nullable=False),
    sa.Column('residence_type', sa.String(length=100), nullable=False),
    sa.Column('residence_address', sa.String(length=255), nullable=False),
    sa.Column('residence_street_number', sa.String(length=20), nullable=False),
    sa.Column('residence_city', sa.String(length=100), nullable=False),
    sa.Column('residence_province', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("birth_date >= DATE '1900-01-01'", name=op.f('ck_people_birth_date_min')),
    sa.CheckConstraint("birth_province ~ '^[A-Za-z]{2}$'", name=op.f('ck_people_birth_province_format')),
    sa.CheckConstraint("phone ~ '^\\+?[0-9]+$'", name=op.f('ck_people_phone_format')),
    sa.CheckConstraint("postal_code ~ '^[0-9]{5}$'", name=op.f('ck_people_postal_code_format')),
    sa.CheckConstraint("residence_province ~ '^[A-Za-z]{2}$'", name=op.f('ck_people_residence_province_format')),
    sa.CheckConstraint('birth_date <= CURRENT_DATE', name=op.f('ck_people_birth_date_max')),
    sa.CheckConstraint('length(tax_code) = 16', name=op.f('ck_people_tax_code_length')),
    sa.CheckConstraint('tax_code = upper(tax_code)', name=op.f('ck_people_tax_code_uppercase')),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_people'))
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
