services:
  postgres:
    image: postgres:17

    container_name: casamichela-postgres-local

    restart: unless-stopped

    environment:
      POSTGRES_DB: casamichela_local
      POSTGRES_USER: casamichela_local_user
      POSTGRES_PASSWORD: local_dev_password

    ports:
      - "5432:5432"

    volumes:
      - ./postgres:/var/lib/postgresql/data
